"""Central configuration for the landing marker perception pipeline."""

CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

DISPLAY_WINDOW_NAME = "Landing Marker Detection"
MASK_WINDOW_NAME = "Processed Mask"

USE_CANNY = True
GAUSSIAN_BLUR_KERNEL = (5, 5)

# Threshold settings used when USE_CANNY is False.
THRESHOLD_VALUE = 80
MAX_BINARY_VALUE = 255

# Canny settings used when USE_CANNY is True.
CANNY_LOW_THRESHOLD = 50
CANNY_HIGH_THRESHOLD = 150

# Contour filtering and ranking.
MIN_CONTOUR_AREA = 1500
MAX_CONTOUR_AREA_RATIO = 0.85
CONTOUR_APPROX_EPSILON_RATIO = 0.02
MIN_ASPECT_RATIO = 0.70
MAX_ASPECT_RATIO = 1.45
MIN_SOLIDITY = 0.80
MIN_EXTENT = 0.55
CONFIDENCE_THRESHOLD = 0.60
READY_TO_LAND_CONFIDENCE = 0.80

# State machine settings.
ALIGNMENT_TOLERANCE = 35
CENTER_TOLERANCE = 20
DOCKED_CONFIRMATION_FRAMES = 10

# Score weights used by the detector.
ASPECT_WEIGHT = 0.35
SOLIDITY_WEIGHT = 0.30
EXTENT_WEIGHT = 0.20
CONVEXITY_WEIGHT = 0.10
VERTEX_WEIGHT = 0.05

# Visual layout and drawing.
FONT = 0  # cv2.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 0.7
FONT_THICKNESS = 2

STATUS_PANEL_X = 20
STATUS_PANEL_Y = 35
STATUS_LINE_HEIGHT = 26

BOX_THICKNESS = 2
CONTOUR_THICKNESS = 2
POINT_RADIUS = 5
LINE_THICKNESS = 2
IMAGE_CENTER_RADIUS = 6
CROSSHAIR_ARM_LENGTH = 14
CENTER_LABEL_OFFSET_X = 12
CENTER_LABEL_OFFSET_Y = 12
LABEL_FONT_SCALE = 0.55
LABEL_THICKNESS = 1
LABEL_TEXT_MIN_Y = 25
IMAGE_CENTER_LINE_THICKNESS = 1

BOX_COLOR = (0, 255, 0)
CONTOUR_COLOR = (255, 0, 0)
TEXT_COLOR = (255, 255, 255)
STATUS_COLOR = (0, 255, 255)
IMAGE_CENTER_COLOR = (0, 255, 255)
LANDING_POINT_COLOR = (0, 0, 255)
LINE_COLOR = (0, 255, 255)
SEARCH_COLOR = (0, 255, 255)
ALIGNED_COLOR = (0, 255, 0)
WARNING_COLOR = (0, 165, 255)
