"""Central configuration for landing marker detection."""

CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

DISPLAY_WINDOW_NAME = "Landing Marker Detection"
MASK_WINDOW_NAME = "Processed Mask"

USE_CANNY = True
GAUSSIAN_BLUR_KERNEL = (5, 5)

# Threshold settings used when USE_CANNY is False.
THRESHOLD_VALUE = 80
MAX_BINARY_VALUE = 255

# Canny settings used when USE_CANNY is True.
CANNY_LOW_THRESHOLD = 50
CANNY_HIGH_THRESHOLD = 150

MIN_CONTOUR_AREA = 1500
MAX_CONTOUR_AREA_RATIO = 0.85
CONTOUR_APPROX_EPSILON_RATIO = 0.02

FONT = 0  # cv2.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 0.7
FONT_THICKNESS = 2

BOX_COLOR = (0, 255, 0)
CONTOUR_COLOR = (255, 0, 0)
TEXT_COLOR = (255, 255, 255)
STATUS_COLOR = (0, 255, 255)

